name: CI Backend

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  ruff:
    name: Ruff
    runs-on: ubuntu-latest
    timeout-minutes: 10

    defaults:
      run:
        working-directory: backend

    steps:
      - name: Baixar o repositorio
        uses: actions/checkout@v6

      - name: Configurar Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.14"

      - name: Instalar Poetry
        run: pipx install poetry==2.4.1

      - name: Instalar dependencias
        run: poetry install --with dev --no-root --no-interaction

      - name: Executar Ruff
        run: poetry run ruff check .

  pytest:
    name: Pytest
    runs-on: ubuntu-latest
    timeout-minutes: 10

    defaults:
      run:
        working-directory: backend

    steps:
      - name: Baixar o repositorio
        uses: actions/checkout@v6

      - name: Configurar Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.14"

      - name: Instalar Poetry
        run: pipx install poetry==2.4.1

      - name: Instalar dependencias
        run: poetry install --with dev --no-root --no-interaction

      - name: Executar testes unitarios
        run: poetry run pytest tests/unit -v

      - name: Executar testes de integracao
        run: poetry run pytest tests/integration -v
